import fs from "fs";
import { fetchItems } from "../src/services/riotApi";

// Curated builds for (almost) all champions.
// Based on standard meta builds (Season 14/15/16 mixed concepts, focusing on iconic items)
const championBuildsByName: Record<string, string[]> = {
  Aatrox: [
    "Profane Hydra",
    "Sundered Sky",
    "Plated Steelcaps",
    "Death's Dance",
    "Spear of Shojin",
    "Sterak's Gage",
  ],
  Ahri: [
    "Malignance",
    "Sorcerer's Shoes",
    "Stormsurge",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
  ],
  Akali: [
    "Lich Bane",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Akshan: [
    "The Collector",
    "Infinity Edge",
    "Berserker's Greaves",
    "Lord Dominik's Regards",
    "Blade of the Ruined King",
    "Rapid Firecannon",
  ],
  Alistar: [
    "Solstice Sleigh",
    "Trailblazer",
    "Ionian Boots of Lucidity",
    "Zeke's Convergence",
    "Knight's Vow",
    "Frozen Heart",
  ],
  Amumu: [
    "Liandry's Anguish",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Abyssal Mask",
    "Thornmail",
    "Jak'Sho, The Protean",
  ],
  Anivia: [
    "Rod of Ages",
    "Archangel's Staff",
    "Sorcerer's Shoes",
    "Liandry's Anguish",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Annie: [
    "Malignance",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Aphelios: [
    "The Collector",
    "Infinity Edge",
    "Berserker's Greaves",
    "Lord Dominik's Regards",
    "Bloodthirster",
    "Runaan's Hurricane",
  ],
  Ashe: [
    "Trinity Force",
    "Kraken Slayer",
    "Berserker's Greaves",
    "Terminus",
    "Guinsoo's Rageblade",
    "Wit's End",
  ],
  "Aurelion Sol": [
    "Rylai's Crystal Scepter",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Archangel's Staff",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Aurora: [
    "Malignance",
    "Cosmic Drive",
    "Sorcerer's Shoes",
    "Liandry's Anguish",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
  ],
  Ambessa: [
    "Eclipse",
    "Sundered Sky",
    "Plated Steelcaps",
    "Black Cleaver",
    "Death's Dance",
    "Sterak's Gage",
  ],
  Azir: [
    "Nashor's Tooth",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Bard: [
    "Bloodsong",
    "Locket of the Iron Solari",
    "Boots of Swiftness",
    "Imperial Mandate",
    "Redemption",
    "Rapid Firecannon",
  ],
  "Bel'Veth": [
    "Kraken Slayer",
    "Stridebreaker",
    "Plated Steelcaps",
    "Blade of the Ruined King",
    "Wit's End",
    "Death's Dance",
  ],
  Blitzcrank: [
    "Celestial Opposition",
    "Zeke's Convergence",
    "Mobility Boots",
    "Knight's Vow",
    "Locket of the Iron Solari",
    "Frozen Heart",
  ],
  Brand: [
    "Liandry's Anguish",
    "Rylai's Crystal Scepter",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Shadowflame",
    "Void Staff",
  ],
  Braum: [
    "Solstice Sleigh",
    "Locket of the Iron Solari",
    "Plated Steelcaps",
    "Knight's Vow",
    "Thornmail",
    "Frozen Heart",
  ],
  Briar: [
    "Eclipse",
    "Sundered Sky",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Black Cleaver",
    "Death's Dance",
  ],
  Caitlyn: [
    "The Collector",
    "Infinity Edge",
    "Berserker's Greaves",
    "Lord Dominik's Regards",
    "Rapid Firecannon",
    "Bloodthirster",
  ],
  Camille: [
    "Trinity Force",
    "Ravenous Hydra",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Spear of Shojin",
    "Death's Dance",
  ],
  Cassiopeia: [
    "Rod of Ages",
    "Archangel's Staff",
    "Rylai's Crystal Scepter",
    "Liandry's Anguish",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ], // No boots!
  "Cho'Gath": [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Thornmail",
    "Kaenic Rookern",
    "Jak'Sho, The Protean",
  ],
  Corki: [
    "Trinity Force",
    "Manamune",
    "Sorcerer's Shoes",
    "Malignance",
    "Eclipse",
    "Rapid Firecannon",
  ],
  Darius: [
    "Trinity Force",
    "Sundered Sky",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Dead Man's Plate",
    "Spirit Visage",
  ],
  Diana: [
    "Lich Bane",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  "Dr. Mundo": [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Spirit Visage",
    "Warmog's Armor",
    "Thornmail",
  ],
  Draven: [
    "Bloodthirster",
    "Infinity Edge",
    "Berserker's Greaves",
    "The Collector",
    "Lord Dominik's Regards",
    "Rapid Firecannon",
  ],
  Ekko: [
    "Lich Bane",
    "Hextech Rocketbelt",
    "Sorcerer's Shoes",
    "Nashor's Tooth",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Elise: [
    "Lich Bane",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Morellonomicon",
    "Void Staff",
  ],
  Evelynn: [
    "Lich Bane",
    "Rabadon's Deathcap",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Void Staff",
    "Banshee's Veil",
  ],
  Ezreal: [
    "Trinity Force",
    "Manamune",
    "Ionian Boots of Lucidity",
    "Spear of Shojin",
    "Serylda's Grudge",
    "Blade of the Ruined King",
  ],
  Fiddlesticks: [
    "Malignance",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Shadowflame",
    "Void Staff",
  ],
  Fiora: [
    "Trinity Force",
    "Ravenous Hydra",
    "Plated Steelcaps",
    "Hullbreaker",
    "Death's Dance",
    "Maw of Malmortius",
  ],
  Fizz: [
    "Lich Bane",
    "Zhonya's Hourglass",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Shadowflame",
    "Void Staff",
  ],
  Galio: [
    "Rod of Ages",
    "Riftmaker",
    "Mercury's Treads",
    "Zhonya's Hourglass",
    "Hollow Radiance",
    "Jak'Sho, The Protean",
  ],
  Gangplank: [
    "Trinity Force",
    "The Collector",
    "Ionian Boots of Lucidity",
    "Infinity Edge",
    "Navori Quickblades",
    "Lord Dominik's Regards",
  ],
  Garen: [
    "Stridebreaker",
    "Phantom Dancer",
    "Berserker's Greaves",
    "Infinity Edge",
    "Dead Man's Plate",
    "Mortal Reminder",
  ],
  Gnar: [
    "Trinity Force",
    "Black Cleaver",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Jak'Sho, The Protean",
    "Randuin's Omen",
  ],
  Gragas: [
    "Lich Bane",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Graves: [
    "Youmuu's Ghostblade",
    "The Collector",
    "Plated Steelcaps",
    "Black Cleaver",
    "Bloodthirster",
    "Infinity Edge",
  ],
  Gwen: [
    "Nashor's Tooth",
    "Riftmaker",
    "Plated Steelcaps",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Cosmic Drive",
  ],
  Hecarim: [
    "Spear of Shojin",
    "Eclipse",
    "Ionian Boots of Lucidity",
    "Black Cleaver",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Heimerdinger: [
    "Liandry's Anguish",
    "Rylai's Crystal Scepter",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Hwei: [
    "Luden's Companion",
    "Horizon Focus",
    "Sorcerer's Shoes",
    "Stormsurge",
    "Shadowflame",
    "Rabadon's Deathcap",
  ],
  Illaoi: [
    "Iceborn Gauntlet",
    "Black Cleaver",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Spirit Visage",
    "Sundered Sky",
  ],
  Irelia: [
    "Blade of the Ruined King",
    "Sundered Sky",
    "Plated Steelcaps",
    "Wit's End",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Ivern: [
    "Moonstone Renewer",
    "Redemption",
    "Ionian Boots of Lucidity",
    "Staff of Flowing Water",
    "Ardent Censer",
    "Chemtech Putrifier",
  ],
  Janna: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Redemption",
    "Ardent Censer",
    "Staff of Flowing Water",
  ],
  "Jarvan IV": [
    "Sundered Sky",
    "Eclipse",
    "Plated Steelcaps",
    "Spear of Shojin",
    "Frozen Heart",
    "Maw of Malmortius",
  ],
  Jax: [
    "Trinity Force",
    "Sundered Sky",
    "Plated Steelcaps",
    "Titanic Hydra",
    "Sterak's Gage",
    "Wit's End",
  ],
  Jayce: [
    "Ecplise",
    "Manamune",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Opportunity",
    "Edge of Night",
  ],
  Jhin: [
    "The Collector",
    "Infinity Edge",
    "Boots of Swiftness",
    "Rapid Firecannon",
    "Lord Dominik's Regards",
    "Bloodthirster",
  ],
  Jinx: [
    "Kraken Slayer",
    "Infinity Edge",
    "Berserker's Greaves",
    "Runaan's Hurricane",
    "Lord Dominik's Regards",
    "Guardian Angel",
  ],
  "K'Sante": [
    "Iceborn Gauntlet",
    "Jak'Sho, The Protean",
    "Plated Steelcaps",
    "Kaenic Rookern",
    "Thornmail",
    "Sunfire Aegis",
  ],
  "Kai'Sa": [
    "Statikk Shiv",
    "Guinsoo's Rageblade",
    "Berserker's Greaves",
    "Nashor's Tooth",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Kalista: [
    "Blade of the Ruined King",
    "Guinsoo's Rageblade",
    "Berserker's Greaves",
    "Runaan's Hurricane",
    "Terminus",
    "Jak'Sho, The Protean",
  ],
  Karma: [
    "Malignance",
    "Cosmic Drive",
    "Ionian Boots of Lucidity",
    "Morellonomicon",
    "Rabadon's Deathcap",
    "Cryptbloom",
  ],
  Karthus: [
    "Malignance",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Kassadin: [
    "Malignance",
    "Rod of Ages",
    "Sorcerer's Shoes",
    "Seraph's Embrace",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Katarina: [
    "Nashor's Tooth",
    "Lich Bane",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Kayle: [
    "Nashor's Tooth",
    "Guinsoo's Rageblade",
    "Berserker's Greaves",
    "Rabadon's Deathcap",
    "Riftmaker",
    "Terminus",
  ],
  Kayn: [
    "Profane Hydra",
    "Opportunity",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Axiom Arc",
    "Edge of Night",
  ], // Blue form default
  Kennen: [
    "Hextech Rocketbelt",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  "Kha'Zix": [
    "Youmuu's Ghostblade",
    "The Collector",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Edge of Night",
    "Opportunity",
  ],
  Kindred: [
    "Kraken Slayer",
    "Trinity Force",
    "Berserker's Greaves",
    "Terminus",
    "Wit's End",
    "Guardian Angel",
  ],
  Kled: [
    "Profane Hydra",
    "Eclipse",
    "Plated Steelcaps",
    "Black Cleaver",
    "Sterak's Gage",
    "Mortal Reminder",
  ],
  "Kog'Maw": [
    "Blade of the Ruined King",
    "Guinsoo's Rageblade",
    "Berserker's Greaves",
    "Runaan's Hurricane",
    "Terminus",
    "Jak'Sho, The Protean",
  ],
  LeBlanc: [
    "Luden's Companion",
    "Stormsurge",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  "Lee Sin": [
    "Sundered Sky",
    "Eclipse",
    "Plated Steelcaps",
    "Black Cleaver",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Leona: [
    "Solstice Sleigh",
    "Locket of the Iron Solari",
    "Plated Steelcaps",
    "Zeke's Convergence",
    "Knight's Vow",
    "Thornmail",
  ],
  Lillia: [
    "Liandry's Anguish",
    "Riftmaker",
    "Ionian Boots of Lucidity",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Cosmic Drive",
  ],
  Lissandra: [
    "Malignance",
    "Zhonya's Hourglass",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Lucian: [
    "The Collector",
    "Navori Quickblades",
    "Ionian Boots of Lucidity",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Rapid Firecannon",
  ],
  Lulu: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Redemption",
    "Ardent Censer",
    "Staff of Flowing Water",
  ],
  Lux: [
    "Luden's Companion",
    "Horizon Focus",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Malphite: [
    "Hollow Radiance",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Thornmail",
    "Frozen Heart",
    "Jak'Sho, The Protean",
  ],
  Malzahar: [
    "Malignance",
    "Rylai's Crystal Scepter",
    "Sorcerer's Shoes",
    "Liandry's Anguish",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Maokai: [
    "Solstice Sleigh",
    "Trailblazer",
    "Boots of Swiftness",
    "Locket of the Iron Solari",
    "Dead Man's Plate",
    "Abyssal Mask",
  ],
  "Master Yi": [
    "Blade of the Ruined King",
    "Guinsoo's Rageblade",
    "Berserker's Greaves",
    "Wit's End",
    "Death's Dance",
    "Guardian Angel",
  ],
  Milio: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Redemption",
    "Ardent Censer",
    "Staff of Flowing Water",
  ],
  "Miss Fortune": [
    "Youmuu's Ghostblade",
    "The Collector",
    "Berserker's Greaves",
    "Edge of Night",
    "Serylda's Grudge",
    "Opportunity",
  ],
  Mordekaiser: [
    "Rylai's Crystal Scepter",
    "Riftmaker",
    "Plated Steelcaps",
    "Liandry's Anguish",
    "Zhonya's Hourglass",
    "Spirit Visage",
  ],
  Morgana: [
    "Zaz'Zak's Realmspike",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Morellonomicon",
    "Rylai's Crystal Scepter",
  ],
  Naafiri: [
    "Profane Hydra",
    "Opportunity",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Edge of Night",
    "Eclipse",
  ],
  Nami: [
    "Dream Maker",
    "Imperial Mandate",
    "Ionian Boots of Lucidity",
    "Moonstone Renewer",
    "Staff of Flowing Water",
    "Ardent Censer",
  ],
  Nasus: [
    "Trinity Force",
    "Frozen Heart",
    "Plated Steelcaps",
    "Spirit Visage",
    "Sterak's Gage",
    "Sundered Sky",
  ],
  Nautilus: [
    "Solstice Sleigh",
    "Zeke's Convergence",
    "Mobility Boots",
    "Knight's Vow",
    "Locket of the Iron Solari",
    "Thornmail",
  ],
  Neeko: [
    "Hextech Rocketbelt",
    "Zhonya's Hourglass",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Nidalee: [
    "Lich Bane",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Nilah: [
    "The Collector",
    "Navori Quickblades",
    "Berserker's Greaves",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Bloodthirster",
  ],
  Nocturne: [
    "Stridebreaker",
    "Hexplate",
    "Plated Steelcaps",
    "Black Cleaver",
    "Death's Dance",
    "Guardian Angel",
  ],
  "Nunu & Willump": [
    "Sunfire Aegis",
    "Liandry's Anguish",
    "Plated Steelcaps",
    "Spirit Visage",
    "Thornmail",
    "Jak'Sho, The Protean",
  ], // TankAP hybrid
  Olaf: [
    "Stridebreaker",
    "Sterak's Gage",
    "Plated Steelcaps",
    "Death's Dance",
    "Spirit Visage",
    "Jak'Sho, The Protean",
  ],
  Orianna: [
    "Seraph's Embrace",
    "Luden's Companion",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Ornn: [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Jak'Sho, The Protean",
    "Thornmail",
    "Kaenic Rookern",
  ],
  Pantheon: [
    "Eclipse",
    "Cleaver",
    "Plated Steelcaps",
    "Sundered Sky",
    "Sterak's Gage",
    "Spear of Shojin",
  ],
  Poppy: [
    "Sunfire Aegis",
    "Iceborn Gauntlet",
    "Plated Steelcaps",
    "Thornmail",
    "Kaenic Rookern",
    "Jak'Sho, The Protean",
  ],
  Pyke: [
    "Bloodsong",
    "Umbral Glaive",
    "Mobility Boots",
    "Youmuu's Ghostblade",
    "Edge of Night",
    "Opportunity",
  ],
  Qiyana: [
    "Profane Hydra",
    "Opportunity",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Edge of Night",
    "Axiom Arc",
  ],
  Quinn: [
    "Stormrazor",
    "Youmuu's Ghostblade",
    "Berserker's Greaves",
    "The Collector",
    "Lord Dominik's Regards",
    "Infinity Edge",
  ],
  Rakan: [
    "Solstice Sleigh",
    "Zeke's Convergence",
    "Ionian Boots of Lucidity",
    "Trailblazer",
    "Knight's Vow",
    "Locket of the Iron Solari",
  ],
  Rammus: [
    "Thornmail",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Jak'Sho, The Protean",
    "Dead Man's Plate",
    "Abyssal Mask",
  ],
  "Rek'Sai": [
    "Stridebreaker",
    "Black Cleaver",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Death's Dance",
    "Guardian Angel",
  ],
  Rell: [
    "Solstice Sleigh",
    "Zeke's Convergence",
    "Plated Steelcaps",
    "Knight's Vow",
    "Locket of the Iron Solari",
    "Trailblazer",
  ],
  "Renata Glasc": [
    "Solstice Sleigh",
    "Locket of the Iron Solari",
    "Ionian Boots of Lucidity",
    "Redemption",
    "Knight's Vow",
    "Ardent Censer",
  ],
  Renekton: [
    "Eclipse",
    "Sundered Sky",
    "Plated Steelcaps",
    "Black Cleaver",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Rengar: [
    "Profane Hydra",
    "Hubris",
    "Ionian Boots of Lucidity",
    "The Collector",
    "Infinity Edge",
    "Lord Dominik's Regards",
  ],
  Riven: [
    "Eclipse",
    "Sundered Sky",
    "Ionian Boots of Lucidity",
    "Black Cleaver",
    "Death's Dance",
    "Maw of Malmortius",
  ],
  Rumble: [
    "Liandry's Anguish",
    "Riftmaker",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Morellonomicon",
    "Rabadon's Deathcap",
  ],
  Ryze: [
    "Rod of Ages",
    "Seraph's Embrace",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Frozen Heart",
    "Void Staff",
  ],
  Samira: [
    "The Collector",
    "Infinity Edge",
    "Plated Steelcaps",
    "Immortal Shieldbow",
    "Lord Dominik's Regards",
    "Bloodthirster",
  ],
  Sejuani: [
    "Sunfire Aegis",
    "Warmog's Armor",
    "Plated Steelcaps",
    "Thornmail",
    "Kaenic Rookern",
    "Jak'Sho, The Protean",
  ],
  Senna: [
    "Bloodsong",
    "Umbral Glaive",
    "Boots of Swiftness",
    "Youmuu's Ghostblade",
    "Rapid Firecannon",
    "Opportunity",
  ],
  Seraphine: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Staff of Flowing Water",
    "Redemption",
    "Ardent Censer",
  ],
  Sett: [
    "Stridebreaker",
    "Sundered Sky",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Hullbreaker",
    "Titanic Hydra",
  ],
  Shaco: [
    "Youmuu's Ghostblade",
    "Profane Hydra",
    "Berserker's Greaves",
    "The Collector",
    "Infinity Edge",
    "Lord Dominik's Regards",
  ],
  Shen: [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Titanic Hydra",
    "Thornmail",
    "Hollow Radiance",
  ],
  Shyvana: [
    "Nashor's Tooth",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Shadowflame",
  ], // AP Shyv
  Singed: [
    "Liandry's Anguish",
    "Rylai's Crystal Scepter",
    "Boots of Swiftness",
    "Riftmaker",
    "Dead Man's Plate",
    "Jak'Sho, The Protean",
  ],
  Sion: [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Titanic Hydra",
    "Hollow Radiance",
    "Jak'Sho, The Protean",
  ],
  Sivir: [
    "Statikk Shiv",
    "Navori Quickblades",
    "Berserker's Greaves",
    "Phantom Dancer",
    "Bloodthirster",
    "Lord Dominik's Regards",
  ],
  Skarner: [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Jak'Sho, The Protean",
    "Thornmail",
    "Kaenic Rookern",
  ],
  Smolder: [
    "Trinity Force",
    "Manamune",
    "Ionian Boots of Lucidity",
    "Spear of Shojin",
    "Rapid Firecannon",
    "Bloodthirster",
  ],
  Sona: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Archangel's Staff",
    "Staff of Flowing Water",
    "Ardent Censer",
  ],
  Soraka: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Redemption",
    "Ardent Censer",
    "Warmog's Armor",
  ],
  Swain: [
    "Rylai's Crystal Scepter",
    "Liandry's Anguish",
    "Plated Steelcaps",
    "Zhonya's Hourglass",
    "Spirit Visage",
    "Riftmaker",
  ],
  Sylas: [
    "Lich Bane",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Syndra: [
    "Luden's Companion",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Stormsurge",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  "Tahm Kench": [
    "Heartsteel",
    "Sunfire Aegis",
    "Plated Steelcaps",
    "Spirit Visage",
    "Thornmail",
    "Jak'Sho, The Protean",
  ],
  Taliyah: [
    "Luden's Companion",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Talon: [
    "Youmuu's Ghostblade",
    "Profane Hydra",
    "Ionian Boots of Lucidity",
    "Axiom Arc",
    "Serylda's Grudge",
    "Edge of Night",
  ],
  Taric: [
    "Solstice Sleigh",
    "Locket of the Iron Solari",
    "Plated Steelcaps",
    "Fimbulwinter",
    "Frozen Heart",
    "Knight's Vow",
  ],
  Teemo: [
    "Nashor's Tooth",
    "Malignance",
    "Sorcerer's Shoes",
    "Liandry's Anguish",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Thresh: [
    "Solstice Sleigh",
    "Locket of the Iron Solari",
    "Mobility Boots",
    "Zeke's Convergence",
    "Knight's Vow",
    "Frozen Heart",
  ],
  Tristana: [
    "Kraken Slayer",
    "Navori Quickblades",
    "Berserker's Greaves",
    "Phantom Dancer",
    "Bloodthirster",
    "Lord Dominik's Regards",
  ],
  Trundle: [
    "Trinity Force",
    "Ravenous Hydra",
    "Plated Steelcaps",
    "Hullbreaker",
    "Blade of the Ruined King",
    "Wit's End",
  ],
  Tryndamere: [
    "Ravenous Hydra",
    "Navori Quickblades",
    "Berserker's Greaves",
    "Phantom Dancer",
    "Infinity Edge",
    "Blade of the Ruined King",
  ],
  "Twisted Fate": [
    "Rod of Ages",
    "Lich Bane",
    "Sorcerer's Shoes",
    "Rapid Firecannon",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
  ],
  Twitch: [
    "Blade of the Ruined King",
    "Runaan's Hurricane",
    "Berserker's Greaves",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Wit's End",
  ],
  Udyr: [
    "Liandry's Anguish",
    "Dead Man's Plate",
    "Boots of Swiftness",
    "Force of Nature",
    "Frozen Heart",
    "Jak'Sho, The Protean",
  ], // Fast tank udyr
  Urgot: [
    "Black Cleaver",
    "Sterak's Gage",
    "Plated Steelcaps",
    "Titanic Hydra",
    "Jak'Sho, The Protean",
    "Thornmail",
  ],
  Varus: [
    "Youmuu's Ghostblade",
    "Opportunity",
    "Ionian Boots of Lucidity",
    "Manamune",
    "Edge of Night",
    "Serylda's Grudge",
  ], // Lethality
  Vayne: [
    "Trinity Force",
    "Kraken Slayer",
    "Berserker's Greaves",
    "Guinsoo's Rageblade",
    "Blade of the Ruined King",
    "Terminus",
  ],
  Veigar: [
    "Luden's Companion",
    "Rabadon's Deathcap",
    "Sorcerer's Shoes",
    "Stormsurge",
    "Shadowflame",
    "Void Staff",
  ],
  "Vel'Koz": [
    "Luden's Companion",
    "Horizon Focus",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Vex: [
    "Luden's Companion",
    "Shadowflame",
    "Sorcerer's Shoes",
    "Zhonya's Hourglass",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Vi: [
    "Sundered Sky",
    "Black Cleaver",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Death's Dance",
    "Guardian Angel",
  ],
  Viego: [
    "Kraken Slayer",
    "Trinity Force",
    "Plated Steelcaps",
    "Sundered Sky",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Viktor: [
    "Luden's Companion",
    "Lich Bane",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Vladimir: [
    "Cosmic Drive",
    "Riftmaker",
    "Ionian Boots of Lucidity",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
    "Void Staff",
  ],
  Volibear: [
    "Riftmaker",
    "Nashor's Tooth",
    "Ionian Boots of Lucidity",
    "Spirit Visage",
    "Thornmail",
    "Jak'Sho, The Protean",
  ],
  Warwick: [
    "Titanic Hydra",
    "Blade of the Ruined King",
    "Plated Steelcaps",
    "Stridebreaker",
    "Sterak's Gage",
    "Spirit Visage",
  ],
  Wukong: [
    "Trinity Force",
    "Sundered Sky",
    "Plated Steelcaps",
    "Black Cleaver",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Xayah: [
    "The Collector",
    "Navori Quickblades",
    "Berserker's Greaves",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Bloodthirster",
  ],
  Xerath: [
    "Luden's Companion",
    "Horizon Focus",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  "Xin Zhao": [
    "Titanic Hydra",
    "Sundered Sky",
    "Plated Steelcaps",
    "Black Cleaver",
    "Sterak's Gage",
    "Death's Dance",
  ],
  Yasuo: [
    "Kraken Slayer",
    "Infinity Edge",
    "Berserker's Greaves",
    "Immortal Shieldbow",
    "Death's Dance",
    "Guardian Angel",
  ],
  Yone: [
    "Blade of the Ruined King",
    "Infinity Edge",
    "Berserker's Greaves",
    "Immortal Shieldbow",
    "Death's Dance",
    "Guardian Angel",
  ],
  Yorick: [
    "Profane Hydra",
    "Trinity Force",
    "Plated Steelcaps",
    "Serylda's Grudge",
    "Opportunity",
    "Hullbreaker",
  ],
  Yuumi: [
    "Dream Maker",
    "Moonstone Renewer",
    "Ionian Boots of Lucidity",
    "Mikael's Blessing",
    "Ardent Censer",
    "Staff of Flowing Water",
  ],
  Zaahen: [
    "Sundered Sky",
    "Titanic Hydra",
    "Plated Steelcaps",
    "Sterak's Gage",
    "Black Cleaver",
    "Death's Dance",
  ], // Bruiser spec
  Zac: [
    "Sunfire Aegis",
    "Spirit Visage",
    "Ionian Boots of Lucidity",
    "Thornmail",
    "Jak'Sho, The Protean",
    "Randuin's Omen",
  ],
  Zed: [
    "Voltaic Cyclosword",
    "Axiom Arc",
    "Ionian Boots of Lucidity",
    "Serylda's Grudge",
    "Opportunity",
    "Edge of Night",
  ],
  Zeri: [
    "Statikk Shiv",
    "Runaan's Hurricane",
    "Berserker's Greaves",
    "Infinity Edge",
    "Bloodthirster",
    "Guardian Angel",
  ],
  Ziggs: [
    "Luden's Companion",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Zilean: [
    "Shurelya's Battlesong",
    "Imperial Mandate",
    "Ionian Boots of Lucidity",
    "Morellonomicon",
    "Cosmic Drive",
    "Frozen Heart",
  ],
  Zoe: [
    "Luden's Companion",
    "Lich Bane",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Void Staff",
  ],
  Zyra: [
    "Zaz'Zak's Realmspike",
    "Liandry's Anguish",
    "Sorcerer's Shoes",
    "Rylai's Crystal Scepter",
    "Morellonomicon",
    "Shadowflame",
  ],
  Mel: [
    "Malignance",
    "Stormsurge",
    "Sorcerer's Shoes",
    "Shadowflame",
    "Rabadon's Deathcap",
    "Zhonya's Hourglass",
  ], // AP Mid spec
  Yunara: [
    "Kraken Slayer",
    "Navori Flickerblade",
    "Berserker's Greaves",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Bloodthirster",
  ], // ADC spec
};

const OUTPUT_FILE = "src/data/championBuilds.ts";

async function main() {
  console.log("Fetching latest items...");
  const items = await fetchItems();

  // Create mapping Name -> ID
  const itemMap: Record<string, string> = {};
  items.forEach((i) => {
    // Normalize names to handle potential small mismatches if needed (e.g. trimming)
    itemMap[i.name] = i.id;
  });

  const finalBuilds: Record<string, string[]> = {};
  const missingItems: Set<string> = new Set();
  const missingchamps: string[] = [];

  for (const [champName, buildNames] of Object.entries(championBuildsByName)) {
    const buildIds: string[] = [];

    for (const itemName of buildNames) {
      // Handle known renames or mismatches manually if needed
      let lookupName = itemName;
      if (lookupName === "Ecplise") lookupName = "Eclipse"; // Typo fix
      if (lookupName === "Cleaver") lookupName = "Black Cleaver"; // Alias
      if (lookupName === "Hexplate") lookupName = "Experimental Hexplate"; // Alias
      if (lookupName === "Blade of the Ruined King")
        lookupName = "Blade of The Ruined King";
      if (lookupName === "Navori Quickblades")
        lookupName = "Navori Flickerblade";
      if (lookupName === "Luden's Companion") lookupName = "Luden's Echo"; // API has Echo
      if (lookupName === "Swiftness Boots") lookupName = "Boots of Swiftness";
      if (lookupName === "Ionian Boots of Lucidity")
        lookupName = "Ionian Boots of Lucidity";
      if (lookupName === "Mobility Boots") lookupName = "Mobility Boots"; // Correct as is

      // Try to find case-insensitive match if direct lookup fails
      let id = itemMap[lookupName];
      if (!id) {
        const lowerName = lookupName.toLowerCase();
        const foundKey = Object.keys(itemMap).find(
          (k) => k.toLowerCase() === lowerName,
        );
        if (foundKey) {
          id = itemMap[foundKey];
        }
      }
      if (id) {
        buildIds.push(id);
      } else {
        missingItems.add(itemName);
        // Fallback or push placeholder? We shouldn't match if item is missing.
        console.warn(`Missing item '${itemName}' for ${champName}`);
      }
    }

    if (buildIds.length === 6) {
      // Use lowercase key for lookup consistency
      finalBuilds[champName.toLowerCase()] = buildIds;
    } else {
      console.warn(
        `Skipping ${champName}, only found ${buildIds.length}/6 items.`,
      );
      missingchamps.push(champName);
    }
  }

  console.log(
    `Prepared builds for ${Object.keys(finalBuilds).length} champions.`,
  );
  if (missingItems.size > 0) {
    console.warn("Global Missing Items:", Array.from(missingItems));
  }

  const fileContent = `// Auto-generated builds.
export const championBuilds: Record<string, string[]> = ${JSON.stringify(finalBuilds, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Wrote to ${OUTPUT_FILE}`);
}

main();
